site_name: Fundamentos Agronómicos
docs_dir: "md"
site_dir: "docs"
#theme: readthedocs
theme: mkdocs
markdown_extensions:
  - admonition
nav:
  - Inicio: index.md
  - UD 1 Identificación de las especies vegetales:
    - Taxonomía Vegetal: FA_UD1_Taxonomía Vegetal.md
    - Célula Vegetal: FA_UD1_La Célula Vegetal.md
    - Tejidos Vegetales: FA_UD1_Los Tejidos Vegetales.md
    - Morfología y Estrucutra de las Plantas: FA_UD1_Morfologia.md
    - Procesos Fisiológicos: FA_UD1_Los Procesos.md
  - UD 2 Características del clima y microclima: 
    - Clima y Microclima: FA_UD2_Clima.md
    - Elementos Climáticos: FA_UD2_Elemetos.md
    - Meteoros: FA_US2_Meteoros.md
    - Aparatos de medida de variables Climáticas: FA_UD2_Aparatos.md
    - Mapas Meteorológicos: FA_UD2_Mapas.md
    - Influencias de las actividades agropecuarias en el clima: FA_UD2_Influencia.md
  - UD 3 El Suelo:
    - El suelo: FA_UD3_El suelo.md
    - El perfil del suelo: FA_UD3_Perfil.md
    - Propiedades Físicas del suelo: FA_UD3_PropFisicas.md
    - Propiedades Químicas del suelo: FA_UD3_PropQuimicas.md
    - Análisis de Suelos: FA_UD3_Analisis.md
  - Sobre Nuestro Centro: about.md
